### ISSUE TITLE
Inconsistency in Figure 6. GeoPackage Minimal Tables for Tiles

### ISSUE THREAD

**Issue by xeonx** [opengeospatial/geopackage#117]
In my understanding as the primary key of `gpkg_tile_matrix_set` is the same as the one of `gpkg_contents` (`table_name`) the association in the diagram should be 1..1 instead of 1..0-*

An other possibility is to have `srs_id` column included in the `gpkg_tile_matrix_set` primary key, allowing to store multiple projections of the same content. But in this case the `srs_id` column shall also be added in the `gpkg_tile_matrix` table and primary key.

**Comment by jyutzler** [comment]
I talked this over with @pdaisey today and we determined that the associations in question should be 1..0-1. The reason for the '0-' is because a gpkg_contents entry doesn't necessarily correspond to a gpkg_tile_matrix_set entry (it might be features instead). We suspect that the '*' multiplicity is an oversight that was not corrected when we prohibited multiple geometry columns per feature table.

It will take me longer to acquire and install the software used to make this diagram than it will to make the actual changes.

**Comment by jyutzler** [comment]
See the [Model](https://github.com/jyutzler/geopackage/tree/model) branch.
https://github.com/jyutzler/geopackage/blob/model/images/geopackage-features.png
https://github.com/jyutzler/geopackage/blob/model/images/geopackage-tiles.png
https://github.com/jyutzler/geopackage/blob/model/images/geopackage-uml.png

**Comment by jyutzler** [comment]
Approved in SWG today. See PR #126
