### ISSUE TITLE
Geopackage sample file "ERDC Whitehorse GeoPackage" is incorrectly formatted

### ISSUE THREAD

**Issue by kimi-AtAvenza** [opengeospatial/geopackage#154]
There are some sample data available on this page (http://www.geopackage.org/#sampledata).  I was investigating the data with a representative from Safe Software.  We conclude that the dataset "ERDC Whitehorse GeoPackage (https://portal.opengeospatial.org/files/63156)" may be incorrectly formatted.  The file cannot be opened with any GIS software. Specifically, it looks like that particular geopackage is missing the geometry column.

**Comment by bosborn** [comment]
I'm not having any problems with it.  The GeoPackage contains only tile data, not features which is why it won't have a geometry column.  It contains a WhiteHorse user tile table with contains an id, zoom_level, tile_column, tile_row, and tile_data column [as defined in the spec](http://www.geopackage.org/spec/#tiles_user_tables).  It is defined in the [Tile Matrix Set](http://www.geopackage.org/spec/#_tile_matrix_set) table and zoom levels 11 through 18 are defined in the [Tile Matrix](http://www.geopackage.org/spec/#tile_matrix) table.

**Comment by kimi-AtAvenza** [comment]
Hi, Brian. Thank you for your message.  I was using FME and Esri to view 
the file and it couldn't open.  Do you know any software to open that 
file (or any raster-tiled geopackage) file?

Thanks,
Kimi

**Comment by bosborn** [comment]
You can look through the [implementations section](http://www.geopackage.org/#implementations) and probably pick something that fits your needs and supports tiles.  I am a developer on the [National Geospatial-Intelligence Agency libraries](http://ngageoint.github.io/GeoPackage/) which includes Java, Android, and iOS repositories.  We do have an example Android app that can be used to view it ([download the APK here](https://github.com/ngageoint/geopackage-mapcache-android/releases/download/1.1/mapcache-1.1.apk)).

**Comment by kimi-AtAvenza** [comment]
Hi, Brian. Thank you for the reply.  I am aware of the page with the 
list on the OGC Geopackage site. I was looking for some desktop software 
to explore the raster-tiled geopackage file... At the moment, I had Esri 
and FME on my machine and neither of the software opens the file.  I 
will also look other software on the list as well, then :)

Also, thank you for the link to the National Geospatial-Intelligence 
Agency Libraries.  I don't use mobiles at this moment but may want to 
look into it with mobiles as an option.

Thanks again!  Have a great day!
- kimi

**Comment by jyutzler** [comment]
Thanks for looking into this, @bosborn.
