### ISSUE TITLE
Guidance for using extensions

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#173]
People have indicated a desire to use certain extensions, but don't know how to go about it.
- [ ] http://www.geopackage.org/spec/#extension_geometry_types
- [ ] others?

If we had some guidance, we could add it to geopackage.org and make it easier for these people.

**Comment by bradh** [comment]
These are fundamentally non-interoperable and should be removed.

**Comment by jyutzler** [comment]
This is OBE because we have removed a number of extensions from 1.2.

**Comment by bradh** [comment]
The Geometry Types Extension (http://www.geopackage.org/spec/#geometry_types_extension) is still in there, and is still not interoperable (because there is no definition for what comes after the number - e.g. I will know its a CURVEPOLYGON, but do I use the points?)

**Comment by pepijnve** [comment]
@bradh not sure why you say this is not interoperable. The WKT and WKB encodings for those types are defined in SQL/MM part 3. See http://jtc1sc32.org/doc/N1101-1150/32N1107-WD13249-3--spatial.pdf sections 5.1.45 and 5.1.46.

**Comment by bradh** [comment]
@pepijnve Does that reference appearr in the geopackage spec?

**Comment by pepijnve** [comment]
Sort of in a very indirect way 😄. 2.1.3.1.1. says the geometry WKB is as specified in OGC 06-103r4 with a footnote that states 

> OGC WKB simple feature geometry types specified in <<9>> are a subset of the ISO WKB geometry types specified in <<12>>

The geometry types extension was intended to allow the rest of the ISO WKB geometry types to be used in a GeoPackage. The reason to have those extra types is that they allows much more of, for instance, GML to be transcoded to GeoPackage. If I remember things correctly (more than 2 years ago already so I might be mistaken) I lobbied for this at the time because at Luciad we wanted to be able to encode AIXM airspace geometry in a GeoPackage. For that we needed curve polygon.

**Comment by jyutzler** [comment]
Reopening so that we can discuss these issues, but I think what @pepijnve wrote is correct.

**Comment by jyutzler** [comment]
In the last week or so, I have produced guidance for using 5 of the 8 registered extensions. Once I finish those off I'll close the issue again.

**Comment by jyutzler** [comment]
http://www.geopackage.org/guidance/getting-started.html
