### ISSUE TITLE
Spec language prevents extension

### ISSUE THREAD

**Issue by bradh** [opengeospatial/geopackage#211]
> [requirement]
> A GeoPackage SHALL only contain data elements, SQL constructs and GeoPackage extensions with the “gpkg” author name specified in this encoding standard.
> 
> In order to guarantee maximum interoperability between applications, GeoPackages SHALL NOT contain data elements (tables or columns), SQL constructs (data types, indexes, constraints or triggers) or extensions that are not specified in this encoding standard.
> SQLite databases that use constructs from the GeoPackage standard but extend those constructs to contain elements not specified in the core GeoPackage standard are referred to as Extended GeoPackages throughout this standard.

That language prevents extensions (unless you are doing .gpkx, which doesn't match user needs as shown in the NSG profile). Its contrary to the approach used in other places (e.g. the elevation extension says to ignore additional columns). Its very hard to test reliably. 

Suggest removing it, and making it clear that users need to handle the possible presence of optional extensions, based on the gpkg_extensions table; and that users need to handle additional columns.

**Comment by jyutzler** [comment]
I believe the current wording matches the intent.

From the introduction:

> An Extended GeoPackage is a GeoPackage that contains any additional data elements (tables or columns) or SQL constructs (data types, functions, indexes, constraints or triggers) that are not specified in this encoding standard.

This is by design. In other words, if your SQLite database contains constructs not in this encoding standard, it is by definition an Extended GeoPackage. In Requirement 3, we note that Extended GeoPackages should have the extension .gpkx, but that it is not required (and apparently will not be done in the NSG profile).

I don't see how this in any way inhibits GeoPackage extensibility.

**Comment by bradh** [comment]
OK. Agree to disagree.

**Comment by jyutzler** [comment]
#328
