### ISSUE TITLE
Deprecate Requirement #69

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#234]
http://www.geopackage.org/spec/#_requirement-69

The SWG determined that it is not possible to comply with this requirement and that it needs to be deprecated.

**Comment by cclark1984** [comment]
It is difficult, if not impossible, to comply with Req 69 "SQL functions that operate on GeoPackageBinary geometries as specified in other extensions SHALL operate correctly on the non-linear geometries specified in this extension." because the functions could have been loaded via an extension such SpatiaLite which cannot be changed, and does not support the non-linear geometries. The removal of this requirement will allow for interoperable storage and retrieval of the geometries, while not requiring but allowing existing functions to work with the geometries.

**Comment by pepijnve** [comment]
Dropping that requirement may cause issues when using non-linear geometry in combination with the spatial index extension since that requires triggers that call ST_Min/MaxX/Y.
In other words, if you drop that requirement then interoperable reading will work; interoperable writing (insert/update of a non-linear geometry into a geopackage created by someone else) may not.

**Comment by jyutzler** [comment]
http://ogc.standardstracker.org/show_request.cgi?id=390
