### ISSUE TITLE
PNG and TIFF Elevation Ancillary Tables Conflict

### ISSUE THREAD

**Issue by bosborn** [opengeospatial/geopackage#257]
Looks like this issue came out of opengeospatial/geopackage-elevation#23

The PNG and TIFF elevation encodings can not use the same ancillary table names with different schemas unless they are not compatible within the same GeoPackage. They should probably be able to both exist within the same GeoPackage.

Both encodings have the tables: gpkg_2d_gridded_coverage_ancillary & gpkg_2d_gridded_tile_ancillary

The PNG encoded ancillary tables have scale and offset columns, the TIFF encoded do not.  If someone was the create TIFF encoded elevation tiles and then attempt to create PNG encoded elevation tiles, this would fail.

The default scale is already 1.0 and default offset is 0.0.  So it is probably best to have a single schema shared by both encodings (the ones listed under PNG). The TIFF encoding can then either rely on the defaults or ignore those columns.  This seems better than making separately named ancillary tables between the two encodings.

**Comment by jyutzler** [comment]
We went back and forth on this at the SWG and ended up in a different place than what I expected. Here were the agreements:

1. It appears to be easier on developers to have a single database schema that is used by both TIFF and PNG. Therefore there will be a single schema which includes the scale and offset columns.
1. We will add a requirement that when using TIFF, the scale and offset SHALL be null and indicate that clients are to ignore this value.
1. We will go back to collapsing to a single extension that allows either TIFF or PNG encodings. We did not have time to go over the exact wording but this is what I have come up with.
   1. The extension name in gpkg_extensions is just `gpkg_elevation_tiles`
   1. (In what is currently requirement 108.5 because of a typographical error, but will eventually be the real Requirement 109), there should be separate data types for 16 and 32-bit and that GeoPackages conforming with this extension MAY support either or both options.
   1. For the 16-bit version, the BLOB type SHALL be PNG
   1. For the 32-bit option, the BLOB type SHALL be TIFF, subject to the constraints currently documented in requirements 129-133
