### ISSUE TITLE
Some Elevation Extension requirements are untestable

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#297]
Requirements 115, 116, and 117 pertain to how values in individual table columns are to be interpreted by client applications. In today's SWG we agreed that they were fundamentally untestable as written and should be rewritten as guidance, not requirements.

**Comment by rouault** [comment]
Regarding req 115 "The min, max, and mean values SHALL be natural, i.e., not scaled or offset. Similarly, the std_dev SHALL be calculated based on the natural values. ", that could potentially be tested on a tile that has some scaling and offseting by recomputing the statistics on the decode tile

Regarding req 116 "Integer elevation values MAY be scaled and offset in order to make more efficient use of 16-bit integer space available in PNG files. The scale and offset MAY be applied to the entire coverage and/or the individual tile. The scale and offset do not apply to the data_null value as defined in Coverage Ancillary Table Definition. ", I agree it is not testable

Regarding req 117 "Floating point elevation values SHALL NOT have a scale and offset applied. The scale and offset values SHALL be null. ", that looks to be testable, at least the part regarding "scale and offset values SHALL be null"

**Comment by jyutzler** [comment]
@rouault The ability to test R115 is vague at best. Keep in mind that we test data encoding compliance, not client operations. Do you really want the test engine to recompute the values and determine if they were calculated properly? I'm not keen on this.
We agree on R116. 
I merged R117 into R112. You can see that in the PR.

**Comment by rouault** [comment]
> Do you really want the test engine to recompute the values and determine if they were calculated properly? I'm not keen on this.

I was just saying that it might be doable, not that it must be compulsary done in the test suite

**Comment by jyutzler** [comment]
I think guidance of how these values are to be interpreted by clients (e.g., https://github.com/opengeospatial/geopackage/pull/298/files#diff-c9ae100661a7dd7363686cdb35da6cc7R124) should be sufficient.

**Comment by jyutzler** [comment]
The SWG voted to modify the pull request. Instead of making the values for the `float` data type null, they should simply use the defaults. This avoids any possible mis-use of "null".

**Comment by rouault** [comment]
@jyutzler The "Table Definition SQL" should be changed to add NOT NULL to the scale and offset columns.

**Comment by jyutzler** [comment]
:+1: b19acc9

**Comment by jyutzler** [comment]
Accepted by SWG today
