### ISSUE TITLE
Clarify "non null" constraint for views

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#395]
Our [DDL](http://www.geopackage.org/spec/#example_feature_table_sql) and [sample feature table or view definition](http://www.geopackage.org/spec/#example_feature_table_sql) indicate that feature tables shall have the NOT NULL constraint on the primary key column. However, because of [the way SQLite does things](http://sqlite.1065341.n5.nabble.com/Difference-in-pragma-table-info-between-tables-and-views-td70491.html), there is no way to check this for views - NOT NULL always comes back false for them.

In response, we should update the ATS/ETS to not require this constraint for views and to provide some explanatory text explaining the situation. This will probably also apply to other content types (tiles, etc.).

**Comment by jyutzler** [comment]
We regularly use the term "updatable view". (For example, [Requirement 29])(http://www.geopackage.org/spec/#r29) Is that really a thing in SQLite? My understanding is no, and this suggests a sweep of the term and a set of corresponding changes. This could be a bit of a chore.

**Comment by rcasscslt** [comment]
Jeff,

There are no "directly" updateable views in SQLite. They are read-only 
at the simplest level. http://www.sqlite.org/lang_createview.html

However, according to : 
https://www.gaia-gis.it/fossil/libspatialite/wiki?name=writable-view, 
you can get the same thing by "tricking" sqlite with triggers. The 
author suggests doing this cautiously though.

Is this a common practice in GeoPackage implementations? Anyone else on 
the list doing this?

If there are no major bureaucratic roadblocks, AND others don't 
typically implement these sorts of view/trigger combos, then we should 
repair the wording.

Otherwise, I am cautiously suggesting defer until the next version, as 
it has no impact on implementations, because it is "technically" 
possible, OR if implementations don't support it, then these will ignore 
it anyway.

-Rob

**Comment by jyutzler** [comment]
Approved by SWG today.
