### ISSUE TITLE
CITE Tests - trigger validation

### ISSUE THREAD

**Issue by KRyden** [opengeospatial/geopackage#413]
The OGC CITE Tests for validation of triggers in a Geopackage need to clearly define what is at issue.  The test appears to be doing a string compare - any difference raises a test failure even if the trigger definition is actually the same as far as SQLite is concerned.  For example, an extra space will raise an error, as will differences in character case and use of “NOT NULL” vs “NOTNULL” (which behave identically in SQLite).  This last case (the NOT NULL vrs NOTNULL) is a real problem because the specification uses both - you can find NOTNULL used four times in the 1.2 version of the standard.

The CITE Tests should always print out what is expected and what is found so that people don't have to experiment to zero in on the difference which actually doesn't matter in SQLite.  

![cite test error for trigger schema](https://user-images.githubusercontent.com/2131460/37314409-d617c0a0-264b-11e8-9070-e2667043de74.png)

Further, if the CITE Tests are going to require character by character compliance then that needs to be stated somewhere so that developers know they have to reproduce strings exactly to comply - even if the difference has no effect on SQLite or the proper processing of the Geopackage.

This type of test compare and reporting creates a lot of work as people fiddle with perfectly working definitions to get a test to pass.  Further, what happens when the standard is corrected for consistency?  Will the tests be maintained? both versions out there forever?  There are likely other CITE Tests working this same way that need to be visited.

**Comment by jyutzler** [comment]
Unfortunately SQLite doesn't give us a great way to verify trigger accuracy. We have developed regexes to verify these things. For example:

> String trigger3d = "CREATE\\sTRIGGER\\s\"?rtree_<t>_<c>_delete\"?\\sAFTER\\sDELETE\\sON\\s\"?<t>\"?\\s?WHEN\\sOLD.\"?<c>\"?\\sNOT\\sNULL\\sBEGIN\\sDELETE\\sFROM\\s\"?rtree_<t>_<c>\"?\\sWHERE\\s\\w*\\s?=\\s?OLD.\"?\\w*\"?;\\s?END";

In the short term, we will update the regexes to be more flexible on whitespace (using `\\s+` or `\\s*` instead of `\\s`).

Honest question: do you want the ETS to provide the regex back to the user as part of the error message? If so we can do that.

This is why sample data is so important. We run unit tests against every sample we can get ahold of (see https://github.com/opengeospatial/ets-gpkg12/blob/master/src/test/java/org/opengis/cite/gpkg12/VerifyTestNGController.java#L56).

If the spec is updated, we will use the versioning mechanism to ensure that that the right test is run against the right version.

**Comment by bosborn** [comment]
My comment from opengeospatial/ets-gpkg12#34

"I was trying to swap out this functionality to something less error prone [in this commit](https://github.com/opengeospatial/ets-gpkg12/pull/34/commits/0d27c4c834e9998747b9dda35cdafbda3d23f783). When testing all the listed GeoPackage examples I was running into issues where some examples did not have PK's (I can't remember which ones), so I backed the changes out. It was basically trying to do a non whitespace comparison so may not be perfect in catching all issues but caused less false validation errors."

**Comment by KRyden** [comment]
As currently implemented, the tests for triggers do not provide enough information for somebody running the test to know what to look for - you end up having to pull the implementation code and the spec and look for differences if they are visible.  Printing out the "Expected" and "Found" information from the test internals would provide a better starting point for somebody running these tests.

Regarding "If the spec is updated, we will use the versioning mechanism to ensure that that the right test is run against the right version." this raises an interesting question....take the UPDATE3 trigger defect described in issue 414.  Issue 414 is a bug - if a bug is identified and corrected, continuing to propagate that bug in earlier releases in order to pass the tests raises a real support and certification issue.  It's a hard problem, but I don't want to chase those bugs indefinitely, particularly when a fix is identified, and propagation of that fix to earlier versions corrects the problem and doesn't impact anything else in that version.

**Comment by jyutzler** [comment]
Let's say we have TRIGGER A (the original one, which is proven to be invalid) and TRIGGER B (the updated one). We'll update the ETS for 1.2 to allow either A or B so that we tests don't reject a 1.2 GeoPackage that contains the corrected trigger. The test for 1.2.1 (or maybe we call it 1.3) will require TRIGGER B.

**Comment by KRyden** [comment]
That works - will need to support cases where the TRIGGER named changed, and where only the body of the trigger changed (as was proposed in the 414 fix) and already applied to the GDAL code line by Evan.

In these cases, I think it would also be useful to print out an informational note that the test passes, but reference the fix available in a later version.
