### ISSUE TITLE
Req 78 equality expectation

### ISSUE THREAD

**Issue by ajanett** [opengeospatial/geopackage#438]
Requirement 78 tests ask for a comparison of equality on items stored as floating point values. These logical statements will always 'Fail' simply due to the nature of comparing floating point values. A tolerance value is required for this test and from the data seen, that tolerance may have to be generous.  
b. SELECT 'Fail' FROM <gtype_test> WHERE ST_MinX(geom) != minx
c. SELECT 'Fail' FROM <gtype_test> WHERE ST_MaxX(geom) != maxx
d. SELECT 'Fail' FROM <gtype_test> WHERE ST_MinY(geom) != miny
e. SELECT 'Fail' FROM <gtype_test> WHERE ST_MaxY(geom) != maxy

**Comment by jyutzler** [comment]
R78 was deleted as part of GeoPackage 1.2. 
http://www.geopackage.org/spec120/#r78

**Comment by ajanett** [comment]
I have test code that tests this requirement without the use of "ST_MinX"... extensions and my approach is using the envelope min/max values (and I am currently testing that implementation).  My issue was with the specification of the test looking for the geometry MinX being **exactly** != the minx of the rtree extents and these will always fail unless there is quite a generous tolerance such as 1.0e-4. I have no issue with the removal of the text immediately following the information and please note that later in the document, this test #78 is still present and I believe it is still a valid test.

**Comment by jyutzler** [comment]
Since the requirement is gone, the test has to go too. We missed this originally but I will take care of it right now.

**Comment by ajanett** [comment]
Sorry to hear that as I have implemented that test and am running it on current geopackages, finding several issues to report.

**Comment by jyutzler** [comment]
OK. This is too late to make the 1.2.1 release. Will you be in Ft. Collins for the TC? It would be good to discuss this issue there.

**Comment by ajanett** [comment]
Currently I have no plans to be in Ft. Collins. Would be happy to discuss this issue or others with you as everyone is available.

**Comment by jyutzler** [comment]
This sounds like a pretty complicated topic. I think we will need you to present your findings to the SWG. If the SWG TC session does not have a full agenda, you could present remotely there (priority goes to those who can present in-person). Otherwise we will schedule a SWG meeting and have you present there.

**Comment by jyutzler** [comment]
In today's SWG meeting, we agreed to issue an informative note indicating the likely use of an index. However, a low-level mandate of how this index should behave is outside of the scope of this standard. In fact, such a mandate may be harmful due to vagueness of what may happen at the boundaries.

This ticket will remain open until the PR for the note is issued and merged.

**Comment by jyutzler** [comment]
Closed by #486
