### ISSUE TITLE
Metadata example in the apendix doesn't match the definition

### ISSUE THREAD

**Issue by liberostelios** [opengeospatial/geopackage#543]
When looking at the metadata example [here](https://www.geopackage.org/spec120/#metadata_example_appendix), the `gpkg_metadata` table is missing the `mime_type` column.

Also, is there a way to validate if metadata is stored correctly?

**Comment by jyutzler** [comment]
The error was already fixed in [GeoPackage 1.2.1](https://www.geopackage.org/spec121/#metadata_example_appendix). 

No, there is no way to validate if metadata is stored correctly. Metadata is open-ended so validation would have to be the responsibility of the system producing the GeoPackage. Alternatively, an external validator could be developed, perhaps in conjunction with a specific profile. For example, if the profile specifies that XXX metadata be used, the validator could check for its presence and conformance. However, this is out of the scope of the GeoPackage Encoding Standard itself.
