### ISSUE TITLE
Test for values that doesn't match the specified types

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#558]
As discussed in https://github.com/opengeospatial/geopackage/issues/530#issuecomment-728906996 and https://github.com/opengeospatial/geopackage/issues/530#issuecomment-728972351, we don't actually test for values that contradict our rules. For example, we don't test whether a DATETIME conforms to `YYYY-MM-DDTHH:MM:SS.SSSZ` or whether a BOOLEAN is actually 0 or 1. 

Fixing this would require additions to the ATS, with a follow-on action to update the [ETS](https://github.com/opengeospatial/ets-gpkg12).

**Comment by jyutzler** [comment]
The SWG is going to take a deeper look at this one. There are two concerns. The first is that this rule might be overly strict. The second is that testing this could take an extremely long time. One possibility to deal with the latter is to have two levels of ETS, a cursory test and a rigorous test.

**Comment by ayoumans** [comment]
I am not sure that this is a real issue or concern BECAUSE the EST does appear to test DATETIME and BOOLEAN broadly and fulfill the requirements of the standard.  Now, theoretically, a test that tests the data is useful, but it does not really test if the GeoPackage is compliant to the standard.  So, if we are just testing if a GeoPackage complies with the standard, I do not think that anything needs to be done.  

For the DATETIME:

According to the specification DATETIME is only required in the gpkg_contents table, as the column name “last_change”.  The gpkg_contents table is a mandatory metadata table.  This is the only place that this is mandatory, so I am assuming that the test should only be testing this table.  

For example, if you have gpkg_metadata, which is an optional table, then you must have a gpkg_metadata_reference table; however, if there is a record, it is mandatory to have the “timestamp” column filled in within the gpkg_metadata_reference table.  I am assuming because gpkg_metadata is not mandatory, then the  gpkg_metadata_reference table should not be tested in the ETS. 

The abstract test suite is found at:  https://github.com/opengeospatial/ets-gpkg12/blob/master/src/main/java/org/opengis/cite/gpkg12/core/DataContentsTests.java

Looking at line 124 it has:  
contentColumns.put("last_change", new ColumnDefinition("DATETIME", true,  false, false, "strftime('%Y-%m-%dT%H:%M:%fZ', 'now')"));  

Now, to my understanding, what this is is saying that for the gpkg_contents table, in the last_change column, the current time should is put in there.  So, unless someone hand-jams something in a record, it should always have the current time in there, in the correct format.  However, that does not prevent someone from putting an incorrect year in there "2061".  

If you go further down in the code, starting with line 179, but really at 197, it looks like the codes does check that individual values in the gpkg_contents table, in the last_change column, are in the proper format.  

To me, it looks like the ATS and the ETS do not need to be updated.  Now, if you produce GeoPackages regularlly, you may want an expanded test to test other optional tables and the information contained within them.

For BOOLEAN:

I was looking and it looks like SQLite does not support a specific Boolean storage type, so Boolean values are stored as integers 0 (false) and 1 (true) and the serial types are 8 (0) and 9 (1), but since SQLite 3.23 it can do Boolean comprehensions.  

I suspect that breaking and testing “Blobs” would take a really long time and that we don’t really want to test the data put into the Blobs.  

Looking at the standard, I do not see a mandatory requirement to use a Boolean, it is however, tested in requirement 5 if you are using a Boolean.   The definition is:  A boolean value representing true or false. Stored as SQLite INTEGER with value 0 for false or 1 for true.”  So, initially, I was thinking that maybe the ETS should be testing individual values to ensure that they are a 0 or 1.  However, because this is not mandatory to use in the standard the ETS does not NEED to test individual values. 

Looking at the ETS, it looks like the column type is tested from 47 to 98 (specifically line 82).  Now, this is only testing that the column data type (format) is correct, it is not testing the records, or if a values are in a column that should not be there—like a “T” or something like that.  Theoretically, you could have incorrect values. 

I can definitely see the value of increased testing, but in terms of the actual standard, only what is mandated in the standard is actually tested, so I think that it is okay.  Is there value in more testing...yes, but I am more inclined to put that burden on the GeoPackage creator at this time in terms of ensuring the content is correct.  For future versions of the GeoPackage, we could tighten requirements.
