### ISSUE TITLE
Coordinate epoch / dynamic CRS

### ISSUE THREAD

**Issue by rouault** [opengeospatial/geopackage#599]
Any geometry referenced in a dynamic CRS, like ITRF2014 or WGS 84 (G1762), should be accompanied with its coordinate epoch (see https://docs.opengeospatial.org/as/18-005r4/18-005r4.html#68).
It would be good to have GeoPackage standardize a metadata to store it.
Should it be at the geometry level or the layer level ?
If at the layer level, one way of doing it would be to standardize something in gpkg_metadata.

Some attempt at that in https://github.com/OSGeo/gdal/pull/3810

Or  put in the definition column of gpkg_spatial_ref_sys the WKT2:2019 COORDINATEMETADATA[] construct ( http://docs.opengeospatial.org/is/18-010r7/18-010r7.html#130 )

**Comment by jyutzler** [comment]
While the epoch should theoretically go in dataset metadata (per ISO 19111 / OGC Topic 2 as approved by OGC in March 2021), we unfortunately do not currently have concurrence on an ISO 19115 profile that would be suitable. Therefore, the only reasonable solution is to add an epoch column to `gpkg_spatial_ref_sys`. I will propose a PR that would modify the existing WKT for CRS extension.

**Comment by rouault** [comment]
> Therefore, the only reasonable solution is to add an epoch column to `gpkg_spatial_ref_sys`

FYI, there is a similar discussion for how to do that in PostGIS in https://trac.osgeo.org/postgis/ticket/4911

**Comment by jratike80** [comment]
Should the topic be added also to the agenda of the new "Features and Geometries JSON SWG" that has kick-off soon (2021-06-01) https://www.ogc.org/projects/groups/featgeojsonswg?

**Comment by rouault** [comment]
Topic raised to Spatialite in https://groups.google.com/g/spatialite-users/c/NtbuBpRzYBE/m/R0-QzgeXAwAJ

**Comment by busstoptaktik** [comment]
> epoch should theoretically go in dataset metadata

@jyutzler one may theorize anything, so "theoretically" anything could be argued for :-)

But *fundamentally* the epoch is a coordinate, so considering it metadata in a geospatial context is only defensible to the extent that you would consider latitude, longitude and elevation as being metadata.

Like elevation, however, time/epoch may need a different kind of treatment than the plane coordinates as the space-time continuum is not a trivial 4D-generalization of the 3D Euclidian space. But historically, the geospatial industry has had great success ignoring the geodetic realities.

While being a good approximation as long as you find meter-level accuracy acceptable, it leads to this kind of patch-working catch-up exercises in the long run. Fortunately @rouault's implementation is admirably light weight and non-intrusive, leaving room and paving the way for a long term truly 4-dimensional approach to geospatial representation systems.

**Comment by SJRowlison** [comment]
Use ISO 19115-1:2014 with its recently released amendments, the amendments take into account dynamic CRS.  Please avoid using ISO 19115:2003 as it is not suitable. ISO 19115-1:2014 was update due to Australia GDA2020 being a dynamic CRS and Australia having a requirement to record epoch. There is also work in-progress between ISO and ESPG registry.

**Comment by rouault** [comment]
> Use ISO 19115-1:2014 with its recently released amendments, the amendments take into account dynamic CRS

I indeed see a ``coordinateEpoch`` in https://github.com/ISO-TC211/XML/blob/master/schemas.isotc211.org/19115/-1/mrs/1.3.0/referenceSystem.xsd#L40 . But that would also imply to redefine the CRS itself by code or inline definitions, which would duplicate the existing information in ``gpkg_spatial_ref_sys``. And presumably we couldn't put just a ``mrs:MD_ReferenceSystem`` but the whole metadata document, which would be a higher barrier for data producers.

**Comment by jyutzler** [comment]
Thank you for your comments, everyone, but the SWG is pretty comfortable with its decision. Use of metadata documents was discarded because there is no path to getting the entire GeoPackage community to agree to implement a specific metadata profile, whether ISO 19115-1:2014 or anything else. The `gpkg_spatial_ref_sys` approach is clean and easily discoverable.

**Comment by cnreediii** [comment]
". . . there is no path to getting the entire GeoPackage community to agree to implement a specific metadata profile,". Same issue in the CDB world which is why CDB 1.x provides an enumeration of allowed metadata standards. The only caveat is that that only one metadata standard or profile of that standard must always be used within a given CDB data store instance. No mixing of standards.
