### ISSUE TITLE
Question regarding the precision of DATETIME values

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/geopackage#648]
How should I understand

> ISO-8601 date/time string in the form YYYY-MM-DDTHH:MM:SS.SSSZ

when it comes to DATETIME values containing fractions of seconds? Is this very strict, in the sense that the precision must be milliseconds, not finer, not coarser?

Or are the following datetimes GeoPackage compliant as well?:
- 2023-02-22T16:00:00.1Z
- 2023-02-22T16:00:00.12Z
- 2023-02-22T16:00:00.1234Z
- 2023-02-22T16:00:00.12345Z

Note: similar questions have been asked in https://github.com/OSGeo/gdal/issues/3423.

**Comment by jyutzler** [comment]
I will give you what I believe to be the technical answer and the practical answer.

### Technical Answer
The GeoPackage Encoding Standard is explicit regarding DATETIME values.

1. [Requirement 5](https://www.geopackage.org/spec131/#r5) governs feature and attribute row/column values of the type DATETIME but the Abstract Test for Requirement 5 does not call for testing every row/column value to ensure that it adheres to the specified type. Therefore using values that do not conform to the specified template will not cause conformance test errors.
2. [Requirement 15](https://www.geopackage.org/spec131/#r15) strictly governs `gpkg_contents.last_change`.
3. [Requirement 100](https://www.geopackage.org/spec131/#r100) strictly governs `gpkg_metadata_reference.timestamp`.

### Practical Answer
Due to the way SQLite handles DATETIME values (or values in general), there is no reasonable way to enforce rigid adherence to something like ISO-8601 in GeoPackage. However, values that stray from the specified templates introduce an interoperability risk, particularly for comparison operations. If this is likely to be an issue in your operational environment, then I recommend testing GeoPackage client behavior to ensure that values with varying precision work as intended.

**Comment by heidivanparys** [comment]
So, just to be sure, the format string given in the GeoPackage spec,

>ISO-8601 date/time string in the form YYYY-MM-DDTHH:MM:SS.SSSZ

has to be interpreted differently than in the [SQLite documentation](https://sqlite.org/lang_datefunc.html#time_values), stating that

> the fractional seconds value SS.SSS can have one or more digits following the decimal point

?

![image](https://user-images.githubusercontent.com/11427611/220889134-27abcc1d-216d-44ca-bf60-407f505a5045.png).

I'm asking because there have been remarks regarding datetimes in a Danish context, stating that GPKG files produced by a certain supplier don't conform to the specification, because they contain datetimes without milliseconds, only seconds precision.

The use cases I'm dealing with would usually be datasets in which the precision would be the same for all values in a DATETIME column. So it's usually not a case of values with varying precision.

**Comment by jyutzler** [comment]
During the 3/7 SWG meeting, we agreed in principle to relax Requirement 5 in this regard. I will be proposing a pull request.
